name: Bug Report
description: Report the bug here
labels: ["Bug"]
assignees:
  - SunkyMP3G
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug here
      placeholder: Bug description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Mod version
      description: What version/content update of the mod are you playing?
      multiple: false
      options:
        - CU-1
        - CU-2 (and .dev)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Other
      description: Are you sure no one has reported this bug? Check [all issues](https://github.com/SunkyMP3G/NetroniumTFS/issues?q=is%3Aissue)
      options:
        - label: I checked other issues to make sure this bug isn't reported or/and fixed
          required: true